"use client";
import supabase from "../config/supabaseClient";

const products = [
{
    id: "01",
    title: "Black Fitted Blazer",
    category: "Top",
    style: ["Work"],
    color: "Black",
    image: "/img/products-img/01-PHST-black-fitted-blazer.png",
    description:
        "A structured black blazer with a tailored waist that defines curves and adds balance to the shoulders and hips.",
    bodyshape: ["Pear", "Hourglass", "Spoon", "Triangle"],
    pairwith: ["Ivory Silk Blouse", "Black Wide-Leg Trousers", "White V-Neck T-Shirt"],
    created_at: new Date().toISOString(),
},
{
    id: "02",
    title: "Ivory Silk Blouse",
    category: "Top",
    style: ["Work"],
    color: "Ivory",
    image: "/img/products-img/02-TISR-ivory-silk-blouse.png",
    description:
        "A classic ivory silk blouse that drapes softly across the shoulders, balancing Inverted Triangle and Rectangle figures while bringing elegance to office looks.",
    bodyshape: ["Triangle", "Inverted Triangle", "Spoon", "Rectangle"],
    pairwith: ["Black Fitted Blazer", "Navy Cable-Knit Sweater", "Grey Flared Pants"],
    created_at: new Date().toISOString(),
},
{
    id: "03",
    title: "White Wrap Top",
    category: "Top",
    style: ["Daily"],
    color: "White",
    image: "/img/products-img/03-SPHIT-white-wrap-top.png",
    description:
        "A feminine wrap top that cinches at the waist to enhance curves, create balance and definition.",
    bodyshape: ["Spoon", "Pear", "Hourglass", "Inverted Triangle", "Triangle"],
    pairwith: ["Black Wide-Leg Trousers", "White Wide-Leg Trousers", "Grey Flared Pants"],
    created_at: new Date().toISOString(),
},
{
    id: "04",
    title: "Navy Cable-Knit Sweater",
    category: "Top",
    style: ["Daily"],
    color: "Navy",
    image: "/img/products-img/04-PT-navy-cable-knit-sweater.png",
    description:
        "A cozy navy sweater with subtle cable texture that adds shape and volume to the upper body, flattering Pear and Triangle shapes while maintaining balance.",
    bodyshape: ["Pear", "Triangle"],
    pairwith: ["White Wide-Leg Trousers", "Black Wide-Leg Trousers", "Grey Flared Pants"],
    created_at: new Date().toISOString(),
},
{
    id: "05",
    title: "White V-Neck T-Shirt",
    category: "Top",
    style: ["Daily"],
    color: "White",
    image: "/img/products-img/05-APHIRS-white-vneck-tshirt.png",
    description:
        "A clean white V-neck tee that elongates the neckline and adds subtle shape.",
    bodyshape: ["Apple", "Pear", "Hourglass", "Inverted Triangle", "Rectangle", "Spoon"],
    pairwith: ["Black Fitted Blazer", "White Wide-Leg Trousers", "Navy Cable-Knit Sweater"],
    created_at: new Date().toISOString(),
},
{
    id: "06",
    title: "Black Wide-Leg Trousers",
    category: "Bottom",
    style: ["Work"],
    color: "Black",
    image: "/img/products-img/06-ISPR2-black-wide-leg-trousers.png",
    description:
        "Elegant black trousers with a wide-leg cut that elongates the legs and balances broader shoulders.",
    bodyshape: ["Inverted Triangle", "Spoon", "Pear", "Rectangle"],
    pairwith: ["Ivory Silk Blouse", "Black Fitted Blazer", "White Wrap Top"],
    created_at: new Date().toISOString(),
},
{
    id: "07",
    title: "Black Satin Wrap Blouse",
    category: "Top",
    style: ["Work"],
    color: "Black",
    image: "/img/products-img/07-SHAI-black-satin-wrap-blouse.png",
    description:
        "A lustrous satin wrap blouse that cinches at the waist and creates a smooth, sophisticated line.",
    bodyshape: ["Spoon", "Hourglass", "Apple", "Inverted Triangle"],
    pairwith: ["Grey Flared Pants", "White Wide-Leg Trousers", "Black Wide-Leg Trousers"],
    created_at: new Date().toISOString(),
},
{
    id: "08",
    title: "Blue Satin Button Blouse",
    category: "Top",
    style: ["Work"],
    color: "Light Blue",
    image: "/img/products-img/08-TI-blue-satin-button-blouse.png",
    description:
        "A light blue satin blouse with tailored seams that enhance the bust and waist.",
    bodyshape: ["Triangle", "Inverted Triangle"],
    pairwith: ["Black Wide-Leg Trousers", "White Wide-Leg Trousers", "Grey Flared Pants"],
    created_at: new Date().toISOString(),
},
{
    id: "09",
    title: "White Wide-Leg Trousers",
    category: "Bottom",
    style: ["Work"],
    color: "White",
    image: "/img/products-img/09-ISPR-white-wide-leg-trousers.png",
    description:
        "Flowy white wide-leg trousers that add volume to the lower body and create balance",
    bodyshape: ["Inverted Triangle", "Spoon", "Rectangle"],
    pairwith: ["Ivory Silk Blouse", "Black Satin Wrap Blouse", "Blue Satin Button Blouse"],
    created_at: new Date().toISOString(),
},
{
    id: "10",
    title: "Grey Flared Pants",
    category: "Bottom",
    style: ["Work"],
    color: "Grey",
    image: "/img/products-img/10-IPSR-grey-flared-pants.png",
    description:
        "Sleek grey flared trousers that create a continuous leg line, flattering Inverted Triangle, Pear, and Spoon body types by balancing proportions.",
    bodyshape: ["Inverted Triangle", "Pear", "Spoon"],
    pairwith: ["Ivory Silk Blouse", "Black Satin Wrap Blouse", "White Wrap Top"],
    created_at: new Date().toISOString(),
},
{
    id: "11",
    title: "Dark Blue Flare Jeans",
    category: "Bottom",
    style: ["Daily"],
    color: "Dark Blue",
    image: "/img/products-img/011-HRPSA-Pants-DarkBlue-FlareJeans.png",
    description:
        "High-rise dark blue flare jeans that lengthen the legs and emphasize the waistline. The gentle flare balances shoulders and hips—flattering for Hourglass, Rectangle, Pear, Spoon, and Apple shapes.",
    bodyshape: ["Hourglass", "Rectangle", "Pear", "Spoon", "Apple"],
    pairwith: ["White V-Neck T-Shirt", "Ivory Silk Blouse", "White Cable-Knit Sweater"],
    created_at: new Date().toISOString(),
},
{
    id: "12",
    title: "Black Wide-Leg Pants",
    category: "Bottom",
    style: ["Work"],
    color: "Black",
    image: "/img/products-img/012-RPTIS-Pants-Black-WideLeg.png",
    description:
        "Elegant black wide-leg trousers that fall straight from the hips to elongate the legs. Ideal for Rectangle, Pear, Triangle, and Inverted Triangle shapes looking for clean proportion.",
    bodyshape: ["Rectangle", "Pear", "Triangle", "Inverted Triangle"],
    pairwith: ["Ivory Silk Blouse", "Blue Satin Button Blouse", "Black Fitted Blazer"],
    created_at: new Date().toISOString(),
},
{
    id: "13",
    title: "Grey Flare Pants",
    category: "Bottom",
    style: ["Work"],
    color: "Grey",
    image: "/img/products-img/013-RHTSV-Pants-Grey-Flare.png",
    description:
        "Tailored grey flare trousers that slim through the thigh before widening below the knee—giving an elongating effect that flatters Rectangle, Hourglass, and Inverted Triangle shapes.",
    bodyshape: ["Rectangle", "Hourglass", "Inverted Triangle"],
    pairwith: ["Black Satin Wrap Blouse", "White Wrap Top", "Ivory Silk Blouse"],
    created_at: new Date().toISOString(),
},
{
    id: "14",
    title: "Navy Wide-Leg Pants",
    category: "Bottom",
    style: ["Work"],
    color: "Navy",
    image: "/img/products-img/014-PATSI-Pants-Navy-WideLeg.png",
    description:
        "Navy wide-leg trousers with a soft drape that enhance movement and balance fuller hips—perfect for Pear, Apple, Triangle, Spoon, and Inverted Triangle figures.",
    bodyshape: ["Pear", "Apple", "Triangle", "Spoon", "Inverted Triangle"],
    pairwith: ["White V-Neck T-Shirt", "Blue Satin Button Blouse", "White Cable-Knit Sweater"],
    created_at: new Date().toISOString(),
},
{
    id: "15",
    title: "Grey Wool Wide-Leg Pants",
    category: "Bottom",
    style: ["Work"],
    color: "Grey",
    image: "/img/products-img/015-AHTSI-Pants-Grey-Wool-WideLeg.png",
    description:
        "Refined grey wool trousers with front pleats that create a soft A-line flow. Ideal for Apple, Hourglass, Triangle, Spoon, and Inverted Triangle shapes.",
    bodyshape: ["Apple", "Hourglass", "Triangle", "Spoon", "Inverted Triangle"],
    pairwith: ["Ivory Silk Blouse", "Black Satin Wrap Blouse", "White Cable-Knit Sweater"],
    created_at: new Date().toISOString(),
},
{
    id: "16",
    title: "Beige Slim-Fit Pants",
    category: "Bottom",
    style: ["Work"],
    color: "Beige",
    image: "/img/products-img/016-RP-Pants-Beige-SlimFit.png",
    description:
        "Slim-fit beige trousers that contour the legs for a sleek office look. Great for Rectangle and Pear shapes wanting clean structure while maintaining a soft silhouette.",
    bodyshape: ["Rectangle", "Pear", "Hourglass"],
    pairwith: ["Ivory Silk Blouse", "Black Fitted Blazer", "White Cable-Knit Sweater"],
    created_at: new Date().toISOString(),
},
{
    id: "17",
    title: "White Satin A-Line Skirt",
    category: "Bottom",
    style: ["Daily", "Work"],
    color: "White",
    image: "/img/products-img/017-RPHASI-Skirt-White-Satin-Aline.png",
    description:
        "A white satin A-line skirt that gently flares from the waist for fluid movement. Perfect for Rectangle, Pear, Hourglass, Spoon, and Inverted Triangle shapes seeking elegance and flow.",
    bodyshape: ["Rectangle", "Pear", "Hourglass", "Spoon", "Inverted Triangle"],
    pairwith: ["White Wrap Top", "Ivory Silk Blouse", "White Cable-Knit Sweater"],
    created_at: new Date().toISOString(),
},
{
    id: "18",
    title: "Black Satin A-Line Skirt",
    category: "Bottom",
    style: ["Daily", "Work"],
    color: "Black",
    image: "/img/products-img/018-RP-Skirt-Black-Satin-Aline.png",
    description:
        "A black satin A-line skirt that enhances curves while maintaining a graceful silhouette—flattering on Rectangle, Pear, Hourglass, and Spoon shapes.",
    bodyshape: ["Rectangle", "Pear", "Hourglass", "Spoon"],
    pairwith: ["Black Satin Wrap Blouse", "White Wrap Top", "White Cable-Knit Sweater"],
    created_at: new Date().toISOString(),
},
{
    id: "19",
    title: "Blue Satin Midi Skirt",
    category: "Bottom",
    style: ["Daily"],
    color: "Royal Blue",
    image: "/img/products-img/019-HATS-Skirt-Blue-Satin-Midi.png",
    description:
        "A royal blue satin midi skirt that moves gracefully and brings attention to the waist. The fluid shape complements Hourglass, Apple, Triangle, and Spoon body types.",
    bodyshape: ["Hourglass", "Apple", "Triangle", "Spoon"],
    pairwith: ["White V-Neck T-Shirt", "Ivory Silk Blouse", "White Cable-Knit Sweater"],
    created_at: new Date().toISOString(),
},
{
    id: "20",
    title: "White Cable-Knit Sweater",
    category: "Top",
    style: ["Daily"],
    color: "White",
    image: "/img/products-img/020-HRS-Sweater-White-CableKnit.png",
    description:
        "A soft white cable-knit sweater with a V-neckline that elongates the upper body. Flattering on Hourglass, Rectangle, and Spoon shapes with a cozy yet refined feel.",
    bodyshape: ["Hourglass", "Rectangle", "Spoon"],
    pairwith: ["Dark Blue Flare Jeans", "Black Satin A-Line Skirt", "Beige Slim-Fit Pants"],
    created_at: new Date().toISOString(),
},
{
    id: "21",
    title: "Black Short-Sleeve Fitted Button Top",
    category: "Top",
    style: ["Work"],
    color: "Black",
    image: "/img/products-img/021-RIS-Top-Black-ShortSleeve-FittedButton.png",
    description:
        "A sleek black short-sleeve button blouse with tailored seams that contour the waist, creating a clean hourglass line. Its fitted shape balances wider hips and enhances upper body definition for Rectangle, Pear, and Spoon figures.",
    bodyshape: ["Rectangle", "Pear", "Spoon"],
    pairwith: ["Black Pencil Skirt", "Beige Slim-Fit Pants", "Navy Wide-Leg Pants"],
    created_at: new Date().toISOString(),
},
{
    id: "22",
    title: "Black Pencil Skirt",
    category: "Bottom",
    style: ["Work"],
    color: "Black",
    image: "/img/products-img/022-RPS-Skirt-Black-Pencil.png",
    description:
        "Classic black pencil skirt that shapes and smooths the lower body. Its straight, narrow cut highlights curves and elongates the frame, offering a polished fit for Hourglass, Rectangle, and Pear body lines.",
    bodyshape: ["Hourglass", "Rectangle", "Pear"],
    pairwith: ["Black Short-Sleeve Fitted Button Top", "Ivory Silk Blouse", "White Cable-Knit Sweater"],
    created_at: new Date().toISOString(),
},
{
    id: "23",
    title: "White Pencil Skirt",
    category: "Bottom",
    style: ["Work"],
    color: "White",
    image: "/img/products-img/023-RPS-Skirt-White-Pencil.png",
    description:
        "Elegant white pencil skirt that offers structure and length. Its clean silhouette refines the hips and waistline, creating a graceful proportion that complements Hourglass, Spoon, and Pear figures.",
    bodyshape: ["Hourglass", "Spoon", "Pear"],
    pairwith: ["Blue Satin Button Blouse", "White V-Neck T-Shirt", "Black Fitted Blazer"],
    created_at: new Date().toISOString(),
},
{
    id: "24",
    title: "Grey Pencil Skirt",
    category: "Bottom",
    style: ["Work"],
    color: "Grey",
    image: "/img/products-img/024-RPS-Skirt-Grey-Pencil.png",
    description:
        "Tailored grey pencil skirt that keeps a crisp and minimal profile. It balances the body by defining the waist while providing smooth vertical lines, flattering Rectangle, Hourglass, and Pear silhouettes.",
    bodyshape: ["Rectangle", "Hourglass", "Pear"],
    pairwith: ["Ivory Silk Blouse", "Black Satin Wrap Blouse", "White Cable-Knit Sweater"],
    created_at: new Date().toISOString(),
},
{
    id: "25",
    title: "Brown Pencil Skirt",
    category: "Bottom",
    style: ["Work"],
    color: "Brown",
    image: "/img/products-img/025-RPS-Skirt-Brown-Pencil.png",
    description:
        "Warm brown pencil skirt that provides gentle contrast and structure. Its fitted waist and sleek taper bring balance to fuller hips and emphasize the body’s natural line, making it flattering for Pear and Spoon figures.",
    bodyshape: ["Pear", "Spoon", "Hourglass"],
    pairwith: ["White Wrap Top", "Black Short-Sleeve Fitted Button Top", "Beige Slim-Fit Pants"],
    created_at: new Date().toISOString(),
},
{
    id: "26",
    title: "Black Square-Neck Fitted Top",
    category: "Top",
    style: ["Daily"],
    color: "Black",
    image: "/img/products-img/026-HRI-Top-Black-SquareNeck-Fitted.png",
    description:
        "Minimalist black top with a square neckline that subtly widens the shoulders and defines the collarbone. Its fitted structure creates balance for Hourglass and Rectangle shapes while adding softness to Spoon silhouettes.",
    bodyshape: ["Hourglass", "Rectangle", "Spoon"],
    pairwith: ["White Satin A-Line Skirt", "Dark Blue Flare Jeans", "Grey Flare Pants"],
    created_at: new Date().toISOString(),
},
{
    id: "27",
    title: "Red Cable-Knit Sweater",
    category: "Top",
    style: ["Daily"],
    color: "Red",
    image: "/img/products-img/027-HRS-Sweater-Red-CableKnit.png",
    description:
        "Rich red cable-knit sweater with a V-neckline that enhances vertical lines. The ribbed knit gently defines curves and adds warmth, making it flattering for Hourglass, Rectangle, and Apple shapes.",
    bodyshape: ["Hourglass", "Rectangle", "Apple"],
    pairwith: ["Black Satin A-Line Skirt", "Grey Wool Wide-Leg Pants", "Dark Blue Flare Jeans"],
    created_at: new Date().toISOString(),
},
{
    id: "28",
    title: "Navy Cable-Knit Sweater",
    category: "Top",
    style: ["Daily"],
    color: "Navy",
    image: "/img/products-img/028-HRS-Sweater-Navy-CableKnit.png",
    description:
        "Navy cable-knit sweater with a V-neck that frames the neckline and adds visual height. The soft knit molds naturally to the body, providing balance and length for Rectangle and Hourglass shapes.",
    bodyshape: ["Rectangle", "Hourglass", "Spoon"],
    pairwith: ["White Pencil Skirt", "Navy Wide-Leg Pants", "Blue Satin Midi Skirt"],
    created_at: new Date().toISOString(),
},
{
    id: "29",
    title: "Black A-Line Skirt",
    category: "Bottom",
    style: ["Daily"],
    color: "Black",
    image: "/img/products-img/029-PRS-Skirt-Black-ALine.png",
    description:
        "Simple black A-line skirt that softly widens from the waist, creating a natural hourglass flow. Its gentle drape conceals the hips and elongates the lower body, making it flattering for Pear and Rectangle shapes.",
    bodyshape: ["Pear", "Rectangle", "Spoon"],
    pairwith: ["Black Short-Sleeve Fitted Button Top", "Ivory Silk Blouse", "White Cable-Knit Sweater"],
    created_at: new Date().toISOString(),
},
{
    id: "30",
    title: "Brown High-Waist Shorts",
    category: "Bottom",
    style: ["Daily"],
    color: "Brown",
    image: "/img/products-img/030-RHS-Shorts-Brown-HighWaist.png",
    description:
        "High-waist brown tailored shorts that structure the midsection and give a long-leg effect. The pleated design creates dimension and balances wider hips for Pear and Hourglass shapes.",
    bodyshape: ["Pear", "Hourglass", "Rectangle"],
    pairwith: ["Black Square-Neck Fitted Top", "White V-Neck T-Shirt", "Blue Satin Button Blouse"],
    created_at: new Date().toISOString(),
},
{
    id: "031",
    title: "White Short-Sleeve Button Shirt",
    category: "Top",
    style: ["Work", "Daily"],
    color: "White",
    image: "/img/products-img/031-HRP-Top-White-ShortSleeve-Button.png",
    description:
      "A crisp white button-up shirt with a structured collar and subtle waist darts that shape the torso. The clean lines elongate the upper body and balance proportions—ideal for Hourglass, Rectangle, and Pear shapes seeking a polished, professional look.",
    bodyshape: ["Hourglass", "Rectangle", "Pear"],
    pairwith: ["Navy Pleated Midi Skirt", "Light Blue Pleated Midi Skirt", "White Cable-Knit Sweater"],
    created_at: new Date().toISOString(),
  },
  
  {
    id: "032",
    title: "Navy Pleated Midi Skirt",
    category: "Skirt",
    style: ["Work", "Daily"],
    color: "Navy",
    image: "/img/products-img/032-HRP-Skirt-Navy-Pleated-Midi.png",
    description:
      "A navy pleated midi skirt with fine vertical folds that create fluid movement and elongate the legs. The fitted waistband defines the waist, making it flattering for Hourglass, Rectangle, and Pear shapes who want an elegant everyday or office piece.",
    bodyshape: ["Hourglass", "Rectangle", "Pear"],
    pairwith: ["White Short-Sleeve Button Shirt", "White Cable-Knit Sweater", "White Fitted Cardigan"],
    created_at: new Date().toISOString(),
  },
  {
    id: "033",
    title: "Yellow Cable Knit V-Neck Sweater",
    category: "Top",
    style: ["Work", "Daily"],
    color: "Yellow",
    image: "/img/products-img/033-HRSA-Sweater-Yellow-CableKnit-VNeck.png",
    description:
      "A cozy yellow cable knit sweater with a flattering V-neckline that adds softness to the upper body—ideal for Rectangle and Spoon shapes to enhance curves and add warmth.",
    bodyshape: ["Rectangle", "Spoon", "Inverted Triangle"],
    pairwith: ["Light Blue Pleated Skirt", "White Wide-Leg Trousers", "Dark Wash Jeans"],
    created_at: new Date().toISOString(),
  },
  
  {
    id: "034",
    title: "White Cable-Knit Crewneck Sweater",
    category: "Top",
    style: ["Work", "Daily"],
    color: "White",
    image: "/img/products-img/034-HR-Sweater-White-CableKnit-CrewNeck.png",
    description:
      "A soft white cable-knit sweater with a gentle fit and ribbed waist hem that adds definition without clinging. The crew neckline and balanced texture make it ideal for Hourglass and Rectangle shapes wanting a cozy yet refined silhouette.",
    bodyshape: ["Hourglass", "Rectangle"],
    pairwith: ["Navy Pleated Midi Skirt", "Light Blue Pleated Midi Skirt", "White Button A-Line Dress"],
    created_at: new Date().toISOString(),
  },
  {
    id: "035",
    title: "Black Knit Off-Shoulder Sweater",
    category: "Top",
    style: ["Daily"],
    color: "Black",
    image: "/img/products-img/035-HIS-Sweater-Black-Knit-OffShoulder.png",
    description:
      "A flirty black off-shoulder knit sweater that highlights the collarbones and balances proportions—perfect for Hourglass and Inverted Triangle shapes aiming for elegant softness.",
    bodyshape: ["Hourglass", "Inverted Triangle", "Rectangle"],
    pairwith: ["High-Waisted Trousers", "Beige Midi Skirt", "Dark Slim Jeans"],
    created_at: new Date().toISOString(),
  },
  
  {
    id: "036",
    title: "Grey Cable Knit Crewneck Sweater",
    category: "Top",
    style: ["Work", "Daily"],
    color: "Grey",
    image: "/img/products-img/036-RSA-Sweater-Grey-CableKnit-CrewNeck.png",
    description:
      "A soft grey cable knit sweater with a classic crew neckline—adds texture and volume to the upper body, making it ideal for Pear and Rectangle shapes seeking balance and cozy style.",
    bodyshape: ["Pear", "Rectangle", "Spoon"],
    pairwith: ["Navy Pleated Midi Skirt", "Black Tailored Pants", "Denim Jeans"],
    created_at: new Date().toISOString(),
  },  
  
  {
    id: "037",
    title: "Light Blue Pleated Midi Skirt",
    category: "Skirt",
    style: ["Work", "Daily"],
    color: "Light Blue",
    image: "/img/products-img/037-HRP-Skirt-LightBlue-Pleated-Midi.png",
    description:
      "A breezy light-blue pleated skirt that falls gracefully below the knee. The fitted waistband cinches the waist while the airy pleats create elegant vertical lines—perfect for Hourglass, Rectangle, and Pear shapes seeking soft, feminine balance.",
    bodyshape: ["Hourglass", "Rectangle", "Pear"],
    pairwith: ["White Short-Sleeve Button Shirt", "White Cable-Knit Sweater", "White Fitted Cardigan"],
    created_at: new Date().toISOString(),
  },
  
  {
    id: "038",
    title: "White Sleeveless Button A-Line Dress",
    category: "Dress",
    style: ["Work", "Daily"],
    color: "White",
    image: "/img/products-img/038-HRP-Dress-White-Button-Aline-Sleeveless.png",
    description:
      "A tailored sleeveless A-line dress with a button-down front that adds subtle structure. The cinched waist and flared skirt create a timeless hourglass illusion—ideal for Hourglass, Rectangle, and Pear shapes who love effortless sophistication.",
    bodyshape: ["Hourglass", "Rectangle", "Pear"],
    pairwith: ["White Fitted Cardigan", "Light Jacket", "Beige Trench Coat"],
    created_at: new Date().toISOString(),
  },
  {
    id: "039",
    title: "White Fitted Knit V-Neck Cardigan",
    category: "Top",
    style: ["Work", "Daily"],
    color: "White",
    image: "/img/products-img/039-HRSA-Cardigan-White-FittedKnit-VNeck.png",
    description:
      "A fitted white V-neck cardigan made from fine knit—perfect for layering while cinching the waist, making it ideal for Spoon, Hourglass, and Rectangle shapes.",
    bodyshape: ["Spoon", "Hourglass", "Rectangle"],
    pairwith: ["Pleated Midi Skirt", "A-Line Dress", "Wide-Leg Trousers"],
    created_at: new Date().toISOString(),
  },  
  
  {
    id: "040",
    title: "Black Belted Sheath Dress",
    category: "Dress",
    style: ["Work"],
    color: "Black",
    image: "/img/products-img/040-HRP-Dress-Black-Sheath-Belted.png",
    description:
      "A fitted black sheath dress with a slim belt accentuating the natural waist. The structured silhouette elongates the body and defines curves—ideal for Hourglass, Rectangle, and Pear shapes seeking a powerful, refined look for work or formal settings.",
    bodyshape: ["Hourglass", "Rectangle", "Pear"],
    pairwith: ["White Fitted Cardigan", "Light Blazer", "Neutral Pumps"],
    created_at: new Date().toISOString(),
  },
  {
    id: "041",
    title: "White Satin Slip Dress",
    category: "Dress",
    style: ["Daily"],
    color: "White",
    image: "/img/products-img/041-HRS-Dress-White-Satin-Slip.png",
    description:
      "A flowing white satin slip dress that hugs the body softly, offering an elegant yet relaxed silhouette. Perfect for casual chic days or romantic evenings. Complements Rectangle, Hourglass, and Spoon body shapes.",
    bodyshape: ["Rectangle", "Hourglass", "Spoon"],
    pairwith: ["Cropped Cardigan", "White Heels", "Pearl Earrings"],
    created_at: new Date().toISOString(),
  },
  {
    id: "042",
    title: "Blue Satin Slip Dress",
    category: "Dress",
    style: ["Daily"],
    color: "Blue",
    image: "/img/products-img/042-HRS-Dress-Blue-Satin-Slip.png",
    description:
      "This baby blue satin slip dress flows effortlessly with every step. Softly draped for daily elegance. Best for Rectangle and Hourglass shapes seeking graceful comfort.",
    bodyshape: ["Rectangle", "Hourglass"],
    pairwith: ["White Knit Cardigan", "Minimalist Sandals", "Silver Necklace"],
    created_at: new Date().toISOString(),
  },
  {
    id: "043",
    title: "Red Fit and Flare Mini Dress",
    category: "Dress",
    style: ["Daily"],
    color: "Red",
    image: "/img/products-img/043-HRS-Dress-Red-FitAndFlare-Mini.png",
    description:
      "A playful red mini dress with a fit and flare shape that enhances waist definition and adds volume to the lower half. Flatters Hourglass, Rectangle, and Pear shapes.",
    bodyshape: ["Hourglass", "Rectangle", "Pear"],
    pairwith: ["White Cardigan", "Heeled Sandals", "Gold Hoops"],
    created_at: new Date().toISOString(),
  },
  {
    id: "044",
    title: "White Corset Top",
    category: "Top",
    style: ["Daily"],
    color: "White",
    image: "/img/products-img/044-HW-Top-White-Corset.png",
    description:
      "A structured white corset top that cinches the waist while maintaining a minimalist look. Great for Hourglass and Rectangle shapes wanting to emphasize curves.",
    bodyshape: ["Hourglass", "Rectangle"],
    pairwith: ["High-Waisted Jeans", "Flowy Skirt", "Minimalist Heels"],
    created_at: new Date().toISOString(),
  },
  {
    id: "045",
    title: "Ivory Belted Midi Dress",
    category: "Dress",
    style: ["Work", "Daily"],
    color: "Ivory",
    image: "/img/products-img/045-HPR-Dress-Ivory-Midi-Belt.png",
    description:
      "A soft ivory belted midi dress that defines the waist and gives a polished look. Suitable for professional or casual settings. Ideal for Hourglass, Spoon, and Pear shapes.",
    bodyshape: ["Hourglass", "Spoon", "Pear"],
    pairwith: ["Beige Blazer", "Neutral Heels", "Crossbody Bag"],
    created_at: new Date().toISOString(),
  },
  {
    id: "046",
    title: "Purple Corset Top",
    category: "Top",
    style: ["Daily"],
    color: "Purple",
    image: "/img/products-img/046-HW-Top-Purple-Corset.png",
    description:
      "A romantic purple corset top that brings focus to the upper body and waist. Great for Rectangle and Hourglass figures looking for a flirty day look.",
    bodyshape: ["Rectangle", "Hourglass"],
    pairwith: ["Light Denim Skirt", "Simple Sandals", "White Shoulder Bag"],
    created_at: new Date().toISOString(),
  },
  {
    id: "047",
    title: "Black Midi Dress with Square Neck and Belt",
    category: "Dress",
    style: ["Work"],
    color: "Black",
    image: "/img/products-img/047-HPR-Dress-Black-Midi-Belt-SquareNeck.png",
    description:
      "A polished black midi dress with a structured belt and square neckline that enhances collarbones and defines the waist. Works best for Hourglass, Inverted Triangle, and Spoon shapes.",
    bodyshape: ["Hourglass", "Inverted Triangle", "Spoon"],
    pairwith: ["Classic Pumps", "Tote Bag", "Trench Coat"],
    created_at: new Date().toISOString(),
  },
  {
    id: "048",
    title: "Black Midi Dress with V-Neck and Belt",
    category: "Dress",
    style: ["Work"],
    color: "Black",
    image: "/img/products-img/048-HPR-Dress-Black-Midi-Belt-VNeck.png",
    description:
      "A black midi dress with a flattering V-neck and cinched waist for a clean and professional silhouette. Complements Pear, Hourglass, and Triangle shapes.",
    bodyshape: ["Pear", "Hourglass", "Triangle"],
    pairwith: ["Black Heels", "Blazer", "Minimalist Jewelry"],
    created_at: new Date().toISOString(),
  },
  {
    id: "049",
    title: "Beige Sleeveless Midi Dress",
    category: "Dress",
    style: ["Work", "Daily"],
    color: "Beige",
    image: "/img/products-img/049-HPR-Dress-Beige-Midi-Sleeveless.png",
    description:
      "A clean beige midi dress with sleeveless tailoring and soft seams. Flatters Spoon, Rectangle, and Hourglass shapes. Suitable for both daily wear and meetings.",
    bodyshape: ["Spoon", "Rectangle", "Hourglass"],
    pairwith: ["White Blazer", "Pointed Flats", "Watch"],
    created_at: new Date().toISOString(),
  },
  {
    id: "050",
    title: "White Pencil Dress with Belt",
    category: "Dress",
    style: ["Work"],
    color: "White",
    image: "/img/products-img/050-HPR-Dress-White-Pencil-Belt.png",
    description:
      "A crisp white pencil dress with a waist belt and clean lines, giving structure to Hourglass and Pear figures. Perfect for a work-ready look.",
    bodyshape: ["Hourglass", "Pear"],
    pairwith: ["Nude Pumps", "Structured Tote", "Gold Watch"],
    created_at: new Date().toISOString(),
  },
  {
    id: "051",
    title: "Black Pencil Dress with Belt",
    category: "Dress",
    style: ["Work"],
    color: "Black",
    image: "/img/products-img/051-HPR-black-pencil-dress-belt.png",
    description:
      "A timeless black pencil dress with a belt that cinches the waist. A smart, classic choice for Hourglass, Spoon, and Triangle shapes.",
    bodyshape: ["Hourglass", "Spoon", "Triangle"],
    pairwith: ["Blazer", "Heeled Loafers", "Silver Studs"],
    created_at: new Date().toISOString(),
  },
  {
    id: "052",
    title: "White Pleated Midi Skirt",
    category: "Bottom",
    style: ["Work", "Daily"],
    color: "White",
    image: "/img/products-img/052-HRP-White-PleatedMidi.png",
    description:
      "An elegant white pleated midi skirt that flows gracefully. A versatile piece for soft office outfits or clean daily looks. Works well for Inverted Triangle, Apple, and Rectangle shapes.",
    bodyshape: ["Inverted Triangle", "Apple", "Rectangle"],
    pairwith: ["Silk Blouse", "Fitted Knit Top", "Cropped Blazer"],
    created_at: new Date().toISOString(),
  },
  

];

export async function insertProducts() {
  const { data, error } = await supabase.from("products").insert(products);

  if (error) {
    console.error("Insert failed:", error.message);
  } else {
    console.log("Products inserted:", data?.length, "items");
  }
}

insertProducts();
